version: '3.8'

services:
  jenkins:
    image:jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/lib/docker/volumes/jenkins_home/_data:/var/jenkins_home 
